title: About Bonha Woo
profile_img: /assets/img/facedemo.jpg
icon_img: /assets/img/icon.png

name: "Hi! I'm Bonha Woo"
job: |
  I am a graduate student at Yonsei University exploring how Computer Vision can connect with diverse domains to reveal new research questions and solutions.

  My work focuses on designing models that reflect the unique characteristics of each domain and developing creative, meaningful approaches to real-world challenges.

phone_number: "+82 10-4058-5172"
address: Seoul, South Korea
email: wbh6589@gmail.com
linkedin_username: BonhaWoo
github_username: RichardWooo
instagram_username: BonhaWoo
twitter_username: RichardWoo97
facebook_username: facebook
youtube_username: youtube
blog_username: anyone_bona
huggingface_username: fuzzbuzz1001
notion_url: https://www.notion.so/Self-Study-Public-2c690fbee19c80d79313fd2a4ef2549a?source=copy_link


# 여기부터가 핵심
# theme: jekyll-professional-resume

# GitHub Pages용 user 페이지면 보통 빈 문자열로 둠
baseurl: ""

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
